#!/bin/bash
# The set command is used to determine action if error
# is encountered.  (-e) will stop and exit (+e) will
# continue with the script.
#set -e

##################################################################################################################
# Author 	: 	Brett Crisp
##################################################################################################################

# Change the number of parallel downloads to 20
echo
echo "Pacman parallel downloads if needed - Arcolinux"
FIND="ParalleDownloads = 8"
REPLACE="ParalleDownloads = 20"
sudo sed -i "s/$FIND/$REPLACE/g" /etc/pacman.conf

echo
echo "Pacman parallel downloads if needed - Arch Linux"
FIND="#ParalleDownloads = 5"
REPLACE="ParalleDownloads = 20"
sudo sed -i "s/$FIND/$REPLACE/g" /etc/pacman.conf

# Update the package lists
sudo pacman -Syyu --noconfirm

# Make executable only the shell scripts in the Personal directory
chmod +x Personal/*.sh

# Change directory to Personal and run each script in order
cd Personal

declare -a scripts=(
  "666-remove-software"
  "100-display-manager"
  "105-install-arcolinux-software"
  "110-install-core-software"
  "120-sound"
  "130-bluetooth"
  "160-laptop"
  "950-fix-pamac-aur"
  "200-software-AUR-repo"
  "700-installing-fonts"
  "900-install-personal-settings-folders"
  "940-btrfs-setup"
  )

for script in "${scripts[@]}"
do
  bash "${script}.sh"
done

# Enable and start bluetooth-autoconnect service after installing from AUR
sudo systemctl enable bluetooth-autoconnect.service
sudo systemctl start bluetooth-autoconnect.service

# Check for errors in enabling or starting the service
if [ $? -ne 0 ]; then
  echo "There was an error with bluetooth-autoconnect service. Check logs."
fi

# Start needed services (the rest were commented out or not applicable)
sudo systemctl enable cronie.service
sudo mkinitcpio -P 

# Create Web Apps
cd /home/brett/.bin-personal
chmod +x *.sh
./web-apps-install.sh

# Notify user that installation is complete
tput setaf 1;
echo "################################################################"
echo "INSTALLATION IS COMPLETE"
echo "ENJOY"
echo "################################################################"
tput sgr0
