#!/bin/bash
# The set command is used to determine action if error
# is encountered.  (-e) will stop and exit (+e) will
# continue with the script.
set -e

##################################################################################################################
# Author 	: 	Brett Crisp
##################################################################################################################

# Update the package lists
sudo pacman -Syyu --noconfirm

# Make executable only the shell scripts in the Personal directory
chmod +x Personal/*.sh

# Change directory to Personal and run each script in order
cd Personal

declare -a scripts=(
  "666-remove-software"
  "100-display-manager"
  "105-install-arcolinux-software"
  "110-install-core-software"
  "120-sound"
  "130-bluetooth"
  "160-laptop"
  "200-software-AUR-repo"
  "700-installing-fonts"
  "900-install-personal-settings-folders"
  "940-btrfs-setup"
  #"950-install-all-fonts-needed-for-conkys-of-arcolinux"
  "955-install-settings-autoconnect-to-bluetooth-headset"
  "997-makepkg-name-email"
  "fix-pamac-aur"
)

for script in "${scripts[@]}"
do
  bash "${script}.sh"
done

# Start needed services
sudo systemctl enable cronie.service
sudo systemctl enable syncthing@brett.service
sudo systemctl enable teamviewerd.service

# Notify user that installation is complete
tput setaf 1;
echo "################################################################"
echo "INSTALLATION IS COMPLETE"
echo "ENJOY"
echo "################################################################"
tput sgr0
