[global/wm]
;margin-bottom = 0
;margin-top = 0

[settings]
screenchange-reload = true
compositing-overline = over
compositing-underline = over
compositing-border = over

[colors]
background = #0a75ad
foreground = #f3f4f5
underline = #5be610

[bar/mainbar-i3-desktop]
monitor = HDMI-1
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 30
background = ${colors.background}
foreground = ${colors.foreground}
radius = 0.0
line-size = 2
line-color = #000000
border-size = 0
padding-left = 0
padding-right = 1
module-margin-left = 1
module-margin-right = 0
font-0 = "FiraCode Nerd Font:size=10:weight=bold"
font-1 = "FiraCode Nerd Font:size=10"
font-2 = "Font Awesome 6 Brands:size=8"
font-3 = "Font Awesome 6 Free:size=12"
font-4 = "Font Awesome:size=10"
modules-left = i3 xwindow
modules-center = date 
modules-right = tray
separator = |
enable-ipc = true
wm-restack = i3

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = false
index-sort = false
enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = false

; Since you're not using icons, these lines can be commented out or removed
; my icon list
;        

;ws-icon-0 = 1;
;ws-icon-1 = 2;
;ws-icon-2 = 3;
;ws-icon-3 = 4;
;ws-icon-4 = 5;
;ws-icon-5 = 6;
;ws-icon-6 = 7;
;ws-icon-7 = 8;
;ws-icon-8 = 9;
;ws-icon-9 = 10;

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-focused = %index%
label-focused-background = #000000
label-focused-foreground = ${colors.foreground}
label-focused-padding = 1
;label-focused-underline = #00FF00
label-unfocused = %index%
label-unfocused-padding = 1
label-unfocused-background = ${colors.background}
label-unfocused-foreground = ${colors.foreground}
label-unfocused-underline = ${colors.background}
label-visible = %icon% %name%
label-visible-background = ${self.label-focused-background}
;label-visible-underline = ${self.label-focused-underline}
;label-visible-underline = ${module/i3.label-focused-underline}
label-visible-padding = 1
label-urgent = %icon% %name%
label-urgent-background = ${self.label-focused-background}
label-urgent-foreground = #db104e
label-urgent-padding = 1
format-foreground = ${colors.foreground}
format-background = ${colors.background}

[module/xwindow]
type = internal/xwindow
enable-click = true
enable-scroll = true
label = %title:0:30:...%
format-font = 2

[module/tray]
type = internal/tray
tray-padding = 4

[module/date]
type = internal/date
interval = 5
date = "%a, %d %B %Y"
time = %H:%M
;format-prefix = "📅 "
format-prefix-foreground = ${colors.underline}
;format-underline = ${colors.underline}
format-foreground = ${colors.foreground}
format-background = ${colors.background}
label = %date% %time%

